# Generated by Django 4.1.1 on 2022-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
