# Generated by Django 4.1.1 on 2022-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_registration_no', models.CharField(max_length=255, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_current_temperature', models.CharField(max_length=255)),
            ],
        ),
    ]
